export const actions = [
  {
    enName: "Muscle Memory",
    id: 0,
    cnName: "坚信",
    groups: "First Turn Only",
    cp: 6,
  },
  {
    enName: "Reflect",
    id: 1,
    cnName: "闲静",
    groups: "First Turn Only",
    cp: 6,
  },
  {
    enName: "Basic Synth",
    id: 2,
    cnName: "制作",
    groups: "Synthesis",
    cp: 0,
  },
  {
    enName: "Careful Synth",
    id: 3,
    cnName: "模范制作",
    groups: "Synthesis",
    cp: 7,
  },
  {
    enName: "Rapid Synth",
    id: 4,
    cnName: "高速制作",
    groups: "Synthesis",
    cp: 0,
  },
  {
    enName: "Focused Synth",
    id: 5,
    cnName: "注视制作",
    groups: "Synthesis",
    cp: 5,
  },
  {
    enName: "Groundwork",
    id: 6,
    cnName: "坯料制作",
    groups: "Synthesis",
    cp: 18,
  },
  {
    enName: "Intensive Synthesis",
    id: 7,
    cnName: "集中制作",
    groups: "Synthesis",
    cp: 6,
    isHQ: true,
  },
  {
    enName: "Prudent Synthesis",
    id: 8,
    cnName: "俭约制作",
    groups: "Synthesis",
    cp: 18,
  },
  {
    enName: "Delicate Synthesis",
    id: 9,
    cnName: "精密制作",
    groups: "Synthesis",
    cp: 32,
  },
  {
    enName: "Basic Touch",
    id: 10,
    cnName: "加工",
    groups: "Quality",
    cp: 18,
  },
  {
    enName: "Hasty Touch",
    id: 11,
    cnName: "仓促",
    groups: "Quality",
    cp: 0,
  },
  {
    enName: "Standard Touch",
    id: 12,
    cnName: "中级加工",
    groups: "Quality",
    cp: 32,
  },
  {
    enName: "Byregots Blessing",
    id: 13,
    cnName: "比尔格的祝福",
    groups: "Quality",
    cp: 24,
  },
  {
    enName: "Precise Touch",
    id: 14,
    cnName: "集中加工",
    groups: "Quality",
    cp: 18,
    isHQ: true,
  },
  {
    enName: "Prudent Touch",
    id: 15,
    cnName: "俭约加工",
    groups: "Quality",
    cp: 25,
  },
  {
    enName: "Focused Touch",
    id: 16,
    cnName: "注视加工",
    groups: "Quality",
    cp: 18,
  },
  {
    enName: "Preparatory Touch",
    id: 17,
    cnName: "坯料加工",
    groups: "Quality",
    cp: 40,
  },
  {
    enName: "Advanced Touch",
    id: 18,
    cnName: "上级加工",
    groups: "Quality",
    cp: 46,
  },
  {
    enName: "Trained Finesse",
    id: 19,
    cnName: "工匠的神技",
    groups: "Quality",
    cp: 32,
  },
  {
    enName: "Master's Mend",
    id: 20,
    cnName: "精修",
    groups: "Durability",
    cp: 88,
  },
  {
    enName: "Waste Not",
    id: 21,
    cnName: "俭约",
    groups: "Durability",
    cp: 56,
  },
  {
    enName: "Waste Not II",
    id: 22,
    cnName: "长期俭约",
    groups: "Durability",
    cp: 98,
  },
  {
    enName: "Manipulation",
    id: 23,
    cnName: "掌握",
    groups: "Durability",
    cp: 96,
  },
  {
    enName: "Veneration",
    id: 24,
    cnName: "崇敬",
    groups: "Buffs",
    cp: 18,
  },
  {
    enName: "Great Stride",
    id: 25,
    cnName: "阔步",
    groups: "Buffs",
    cp: 32,
  },
  {
    enName: "Innovation",
    id: 26,
    cnName: "改革",
    groups: "Buffs",
    cp: 18,
  },
  {
    enName: "Observation",
    id: 27,
    cnName: "观察",
    groups: "Other",
    cp: 7,
  },
  {
    enName: "Tricks of the Trade",
    id: 28,
    cnName: "秘诀",
    groups: "Other",
    cp: 0,
    isHQ: true,
  },
  {
    enName: "Final Appraisal",
    id: 29,
    cnName: "最终确认",
    groups: "Other",
    cp: 1,
  },
  {
    enName: "Heart And Soul",
    id: 30,
    cnName: "专心致志",
    groups: "Other",
    cp: 0,
  },
];
